export const actionTypes = {
  SWITCH_TO_UZBEK: "SWITCH_TO_UZBEK",
  SWITCH_TO_RUSSIAN: "SWITCH_TO_RUSSIAN",
  SWITCH_LANG: "SWITCH_LANG",

  GET_PRODUCTS: "GET_PRODUCTS",
  GET_CATEGORIES: "GET_CATEGORIES",
  GET_PRODUCTS_BY_IDS: "GET_PRODUCTS_BY_IDS",
  GET_SUPPLIERS:"GET_SUPPLIERS",
  GET_CERTIFICATES:"GET_CERTIFICATES",
  GET_CLIENTS:"GET_CLIENTS",
  
  _PENDING: "_PENDING",
  _FULFILLED: "_FULFILLED",
  _REJECTED: "_REJECTED",

  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
  CLEAN_CART: "CLEAN_CART",
};

export default actionTypes;
